import SideNavbar from "../../components/sideNavBar"
import SidePanel from "../../components/sidePanel"
import BottomNavBar from "../../components/bottomNavBar"
import styles from "./Layout.module.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <div className={styles.layout}>
          <SidePanel/>
          <main>{children}</main>
          <BottomNavBar/>
        </div>
      </body>
    </html>
  )
}
